### ISSUE TITLE
Media Card component test cases

### ISSUE THREAD

**Issue by thescientist13** [AnalogStudiosRI/www.blissri.com#40]
## Summary
Coming out of #10 / #21, a Media Card component was created, but no test cases or Storybook were added.  😱 

## Details
1.  [ ] Create Storybook
    - image
    - video
1. [ ] Add test cases, one for each
    - image
    - video

**Comment by luminaire-dev** [comment]
@thescientist13 I can take this one on. 🙋🏻‍♀️ Since the media card component is not merged do you want me to branch from your branch in https://github.com/AnalogStudiosRI/www.blissri.com/pull/21 or commit directly to the https://github.com/AnalogStudiosRI/www.blissri.com/pull/21 PR?

Looks like I will also need write access to the repo.

**Comment by thescientist13** [comment]
Thanks again!  🙌
